//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoroVenvManager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoroVenvManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Please check the location of .python-version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckDotPythonVersionLocation {
            get {
                return ResourceManager.GetString("CheckDotPythonVersionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check the set global version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckSetGlobalVersion {
            get {
                return ResourceManager.GetString("CheckSetGlobalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check the version set in the folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckVersionInFolder {
            get {
                return ResourceManager.GetString("CheckVersionInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check the version set In the folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckVersionSetInFolder {
            get {
                return ResourceManager.GetString("CheckVersionSetInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   === に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandResponseEndMarker {
            get {
                return ResourceManager.GetString("CommandResponseEndMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configurable Version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigurableVersion {
            get {
                return ResourceManager.GetString("ConfigurableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Installation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmInstallation {
            get {
                return ResourceManager.GetString("ConfirmInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy the Template. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyTemplate {
            get {
                return ResourceManager.GetString("CopyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create .venv. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateVenvDirectory {
            get {
                return ResourceManager.GetString("CreateVenvDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating a virtual environment.:
        ///Please press the &apos;Select&apos; button to choose a folder.Select a template from the ComboBox.
        ///Press the &apos;Create&apos; button to create the virtual environment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateVenvTabInfoLabelTex {
            get {
                return ResourceManager.GetString("CreateVenvTabInfoLabelTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloadable Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadableVersion {
            get {
                return ResourceManager.GetString("DownloadableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloaded Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownloadedVersion {
            get {
                return ResourceManager.GetString("DownloadedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the correct folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterCorrectFolder {
            get {
                return ResourceManager.GetString("EnterCorrectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterFolder {
            get {
                return ResourceManager.GetString("EnterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the folder before setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterFolderBeforeSetting {
            get {
                return ResourceManager.GetString("EnterFolderBeforeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plese, enter the version before setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterVersionBeforeSetting {
            get {
                return ResourceManager.GetString("EnterVersionBeforeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the version to install. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterVersionToInstall {
            get {
                return ResourceManager.GetString("EnterVersionToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plese, enter version to set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnterVersionToSet {
            get {
                return ResourceManager.GetString("EnterVersionToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file path is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilePathEmpty {
            get {
                return ResourceManager.GetString("FilePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file path contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilePathInvalidCharacters {
            get {
                return ResourceManager.GetString("FilePathInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to access the specified folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderAccessDenied {
            get {
                return ResourceManager.GetString("FolderAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder is not empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderNotEmpty {
            get {
                return ResourceManager.GetString("FolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder to set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderToSet {
            get {
                return ResourceManager.GetString("FolderToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting the global version: Please enter the version. It will be set when you press the &apos;Set&apos; button. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GlobalVersionTabInfoLabelText {
            get {
                return ResourceManager.GetString("GlobalVersionTabInfoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installation complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing Python {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallPythonVersion {
            get {
                return ResourceManager.GetString("InstallPythonVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install Python: Please enter the version. Press the &apos;Run&apos; button to start the installation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallTabInfoLavelText {
            get {
                return ResourceManager.GetString("InstallTabInfoLavelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFileNameCharacters {
            get {
                return ResourceManager.GetString("InvalidFileNameCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The correct folder is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidFolderSettingMessage {
            get {
                return ResourceManager.GetString("InvalidFolderSettingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The version contains invalid characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidVersionCharacters {
            get {
                return ResourceManager.GetString("InvalidVersionCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting the local version: Please press the &apos;Select&apos; button to choose a folder. Enter the version. Press the &apos;Set&apos; button to apply the settings.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocalVersionTabInfoLabelText {
            get {
                return ResourceManager.GetString("LocalVersionTabInfoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install Pyenv: When you press the &apos;Run&apos; button, pyenv-win will be installed, and the environment variables will be set to make pyenv-win usable.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PyenvTabInfoLabelText {
            get {
                return ResourceManager.GetString("PyenvTabInfoLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the correct folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectCorrectFolder {
            get {
                return ResourceManager.GetString("SelectCorrectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectedFolderNotFound {
            get {
                return ResourceManager.GetString("SelectedFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the global version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetGlobalVersion {
            get {
                return ResourceManager.GetString("SetGlobalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting the local version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetLocalVersion {
            get {
                return ResourceManager.GetString("SetLocalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingCompleted {
            get {
                return ResourceManager.GetString("SettingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Venv environment creation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartVenvCreation {
            get {
                return ResourceManager.GetString("StartVenvCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template will not be copied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateNotCopied {
            get {
                return ResourceManager.GetString("TemplateNotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplateNotSelected {
            get {
                return ResourceManager.GetString("TemplateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Templates folder not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplatesFolderNotFound {
            get {
                return ResourceManager.GetString("TemplatesFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TemplatesNotFound に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemplatesNotFound {
            get {
                return ResourceManager.GetString("TemplatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updateing pip. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdatePip {
            get {
                return ResourceManager.GetString("UpdatePip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Venv environment has been created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VenvCreated {
            get {
                return ResourceManager.GetString("VenvCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Venv environment creation completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VenvCreationCompleted {
            get {
                return ResourceManager.GetString("VenvCreationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder for creating the Venv environment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VenvCreationFolder {
            get {
                return ResourceManager.GetString("VenvCreationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder for creating the Venv environment is not empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VenvFolderNotEmpty {
            get {
                return ResourceManager.GetString("VenvFolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The VENV_HOME environment variable is not set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VenvHomeNotSet {
            get {
                return ResourceManager.GetString("VenvHomeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The version has not been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionNotSet {
            get {
                return ResourceManager.GetString("VersionNotSet", resourceCulture);
            }
        }
    }
}
